# inspired by https://github.com/BinaryBirds/Sunlight


x = None


def mainmenu():
    print ()
    _input = input ("Would you like to generate a datafile? [y]/n ")
    if _input == "" or _input == "y" or _input == "Y":
        return True
    else:
        return False


def print_results(self, extended="no"):
    if extended == "no":
        print()
        print (f"On this date, there are {x} hours of sunlight.")
        print (f"     ...dawn begins at ")
        print (f"     ...sunrise is at ")
        print (f"     ...solar noon is at ")
        print (f"     ...sunset is at ")
        print (f"     ...dusk ends at ")
    elif extended == "yes":
        print()
        print (f"On this date, there are {x} hours of sunlight.")
        print (f"     ...astronomical dawn is at .")
        print (f"     ...nautical dawn is at .")
        print (f"     ...civil dawn is at .")
        print (f"     ...the morning 'blue hour' begins at {x} and ends at {x}.")
        print (f"     ...sunrise is at ")
        print (f"     ...the morning 'golden hour' ends at {x}.")
        print (f"     ...solar noon is at {x}, when the sun is {x} degrees above the horizon.")
        print (f"     ...the evening 'golden hour' begins at {x}.")
        print (f"     ...sunset is at ")
        print (f"     ...the evening 'blue hour' begins at {x} and ends at {x}.")
        print (f"     ...civil dusk is at .")
        print (f"     ...nautical dusk is at .")
        print (f"     ...astronomical dusk is at .")
    else:
        pass

def print_table():
    """Inspired by https://aa.usno.navy.mil/data/docs/RS_OneYear.php"""
    print()
    print (18 * ".", "Sunrise and sunset times for YEAR XXXX", 18 * ".")
    print (33 * ".", "at CORDU", 33 * ".")
    print ("Longitude: W +000 +00", 54 * ".")
    print ("Latitude:  N  +00 +00", 25 * ".", "Time zone: Local Solar", 5 * ".")
    print ()
    print ("DAY/MONTH   01     02     03     04     05     06    Mid     07     08     09     10     11     12     13 ")
    print ("01 Rise   hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm")
    print ("   Set    hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm")
    print ()
    print ("02 Rise   hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm         hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm")
    print ("   Set    hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm         hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm")
    print ()
    print ("03 Rise   hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm         hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm")
    print ("   Set    hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm         hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm")
    print ()
    print ("04 Rise   hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm         hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm")
    print ("   Set    hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm         hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm")
    print ()
    print ("05 Rise   hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm         hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm")
    print ("   Set    hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm         hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm")
    print ()
    print ("06 Rise   hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm         hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm")
    print ("   Set    hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm         hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm")
    print ()
    print ("07 Rise   hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm         hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm")
    print ("   Set    hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm         hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm")
    print ()
    print ("08 Rise   hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm         hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm")
    print ("   Set    hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm         hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm")
    print ()
    print ("09 Rise   hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm         hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm")
    print ("   Set    hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm         hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm")
    print ()
    print ("10 Rise   hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm         hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm")
    print ("   Set    hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm         hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm")
    print ()
    print ("11 Rise   hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm         hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm")
    print ("   Set    hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm         hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm")
    print ()
    print ("12 Rise   hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm         hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm")
    print ("   Set    hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm         hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm")
    print ()
    print ("13 Rise   hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm         hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm")
    print ("   Set    hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm         hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm")
    print ()
    print ("14 Rise   hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm         hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm")
    print ("   Set    hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm         hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm")
    print ()
    print ("15 Rise   hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm         hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm")
    print ("   Set    hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm         hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm")
    print ()
    print ("16 Rise   hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm         hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm")
    print ("   Set    hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm         hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm")
    print ()
    print ("17 Rise   hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm         hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm")
    print ("   Set    hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm         hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm")
    print ()
    print ("18 Rise   hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm         hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm")
    print ("   Set    hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm         hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm")
    print ()
    print ("19 Rise   hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm         hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm")
    print ("   Set    hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm         hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm")
    print ()
    print ("20 Rise   hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm         hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm")
    print ("   Set    hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm         hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm")
    print ()
    print ("21 Rise   hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm         hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm")
    print ("   Set    hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm         hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm")
    print ()
    print ("22 Rise   hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm         hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm")
    print ("   Set    hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm         hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm")
    print ()
    print ("23 Rise   hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm         hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm")
    print ("   Set    hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm         hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm")
    print ()
    print ("24 Rise   hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm         hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm")
    print ("   Set    hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm         hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm")
    print ()
    print ("25 Rise   hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm         hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm")
    print ("   Set    hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm         hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm")
    print ()
    print ("26 Rise   hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm         hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm")
    print ("   Set    hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm         hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm")
    print ()
    print ("27 Rise   hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm         hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm")
    print ("   Set    hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm         hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm")
    print ()
    print ("28 Rise   hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm         hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm")
    print ("   Set    hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm         hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm  hh:mm")
    print ()
